version: '3.8'

services:
  simplify-app:
    build: .
    container_name: simplify-language-local
    volumes:
      - ./logs:/app/logs
      - ./_streamlit_app:/app/_streamlit_app
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      #- METRICS_PORT=8000
    ports:
      - "8501:8501"
      - "8000:8000"
    command: ["streamlit", "run", "/app/_streamlit_app/simplify-language.py", "--server.port=8501", "--server.address=0.0.0.0"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8501 || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  
  prometheus:
    image: prom/prometheus:latest
    container_name: simplify-prometheus-local
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data-local:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      simplify-app:
        condition: service_healthy
    
  grafana:
    image: grafana/grafana:latest
    container_name: simplify-grafana-local
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_ROOT_URL=http://localhost:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data-local:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  prometheus-data-local:
  grafana-data-local:
