global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'simplify_app_metrics'
    static_configs:
      - targets: ['simplify-language-local:8000']
    scrape_interval: 15s
    scrape_timeout: 10s
