apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: DS_PROMETHEUS
    isDefault: true
    jsonData:
      timeInterval: "15s"
      httpMethod: "GET"
    editable: true
